package com.yapu.archive.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.yapu.archive.dao.itf.SysTreeTempletDAO;
import com.yapu.archive.entity.SysTreeTemplet;
import com.yapu.archive.entity.SysTreeTempletExample;

public class SysTreeTempletDAOImpl extends SqlMapClientDaoSupport implements SysTreeTempletDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysTreeTempletDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int countByExample(SysTreeTempletExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SYS_TREE_TEMPLET.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int deleteByExample(SysTreeTempletExample example) {
        int rows = getSqlMapClientTemplate().delete("SYS_TREE_TEMPLET.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int deleteByPrimaryKey(String treeTempletId) {
        SysTreeTemplet key = new SysTreeTemplet();
        key.setTreeTempletId(treeTempletId);
        int rows = getSqlMapClientTemplate().delete("SYS_TREE_TEMPLET.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void insert(SysTreeTemplet record) {
        getSqlMapClientTemplate().insert("SYS_TREE_TEMPLET.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void insertSelective(SysTreeTemplet record) {
        getSqlMapClientTemplate().insert("SYS_TREE_TEMPLET.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public List selectByExample(SysTreeTempletExample example) {
        List list = getSqlMapClientTemplate().queryForList("SYS_TREE_TEMPLET.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysTreeTemplet selectByPrimaryKey(String treeTempletId) {
        SysTreeTemplet key = new SysTreeTemplet();
        key.setTreeTempletId(treeTempletId);
        SysTreeTemplet record = (SysTreeTemplet) getSqlMapClientTemplate().queryForObject("SYS_TREE_TEMPLET.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByExampleSelective(SysTreeTemplet record, SysTreeTempletExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_TREE_TEMPLET.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByExample(SysTreeTemplet record, SysTreeTempletExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_TREE_TEMPLET.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByPrimaryKeySelective(SysTreeTemplet record) {
        int rows = getSqlMapClientTemplate().update("SYS_TREE_TEMPLET.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByPrimaryKey(SysTreeTemplet record) {
        int rows = getSqlMapClientTemplate().update("SYS_TREE_TEMPLET.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private static class UpdateByExampleParms extends SysTreeTempletExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysTreeTempletExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}