package com.yapu.archive.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.yapu.archive.dao.itf.SysTableDAO;
import com.yapu.archive.entity.SysTable;
import com.yapu.archive.entity.SysTableExample;

public class SysTableDAOImpl extends SqlMapClientDaoSupport implements SysTableDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public SysTableDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int countByExample(SysTableExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SYS_TABLE.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int deleteByExample(SysTableExample example) {
        int rows = getSqlMapClientTemplate().delete("SYS_TABLE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int deleteByPrimaryKey(String tableid) {
        SysTable key = new SysTable();
        key.setTableid(tableid);
        int rows = getSqlMapClientTemplate().delete("SYS_TABLE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public void insert(SysTable record) {
        getSqlMapClientTemplate().insert("SYS_TABLE.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public void insertSelective(SysTable record) {
        getSqlMapClientTemplate().insert("SYS_TABLE.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public List<SysTable> selectByExample(SysTableExample example) {
        List<SysTable> list = getSqlMapClientTemplate().queryForList("SYS_TABLE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public SysTable selectByPrimaryKey(String tableid) {
        SysTable key = new SysTable();
        key.setTableid(tableid);
        SysTable record = (SysTable) getSqlMapClientTemplate().queryForObject("SYS_TABLE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int updateByExampleSelective(SysTable record, SysTableExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_TABLE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int updateByExample(SysTable record, SysTableExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_TABLE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int updateByPrimaryKeySelective(SysTable record) {
        int rows = getSqlMapClientTemplate().update("SYS_TABLE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public int updateByPrimaryKey(SysTable record) {
        int rows = getSqlMapClientTemplate().update("SYS_TABLE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    private static class UpdateByExampleParms extends SysTableExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysTableExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}