package com.yapu.system.dao.itf;

import java.util.List;

import com.yapu.system.entity.SysConfig;
import com.yapu.system.entity.SysConfigExample;

public interface SysConfigDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int countByExample(SysConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int deleteByExample(SysConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int deleteByPrimaryKey(String configid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    void insert(SysConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    void insertSelective(SysConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    List selectByExample(SysConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    SysConfig selectByPrimaryKey(String configid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByExampleSelective(SysConfig record, SysConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByExample(SysConfig record, SysConfigExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByPrimaryKeySelective(SysConfig record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_CONFIG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByPrimaryKey(SysConfig record);
}