package com.yapu.system.dao.itf;

import java.util.HashMap;
import java.util.List;

import com.yapu.system.entity.SysOperatelog;
import com.yapu.system.entity.SysOperatelogExample;

public interface SysOperatelogDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int countByExample(SysOperatelogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int deleteByExample(SysOperatelogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int deleteByPrimaryKey(String operatelogid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    void insert(SysOperatelog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    void insertSelective(SysOperatelog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    List selectByExample(SysOperatelogExample example);
    
    /**
     * 手动加入的分页语句
     * @param map
     * @return
     */
    List selectByMapPage(HashMap map);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    SysOperatelog selectByPrimaryKey(String operatelogid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByExampleSelective(SysOperatelog record, SysOperatelogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByExample(SysOperatelog record, SysOperatelogExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByPrimaryKeySelective(SysOperatelog record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_OPERATELOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByPrimaryKey(SysOperatelog record);
}