package com.yapu.archive.dao.itf;

import java.util.HashMap;
import java.util.List;

import com.yapu.archive.entity.ArRelease;
import com.yapu.archive.entity.ArReleaseExample;

public interface ArReleaseDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int countByExample(ArReleaseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int deleteByExample(ArReleaseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int deleteByPrimaryKey(String releaseid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    void insert(ArRelease record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    void insertSelective(ArRelease record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    List selectByExample(ArReleaseExample example);
    
    /**
     * 手动加入的分页语句
     * @param map
     * @return
     */
    List selectByMapPage(HashMap map);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    ArRelease selectByPrimaryKey(String releaseid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByExampleSelective(ArRelease record, ArReleaseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByExample(ArRelease record, ArReleaseExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByPrimaryKeySelective(ArRelease record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table AR_RELEASE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByPrimaryKey(ArRelease record);
}