package com.yapu.archive.dao.itf;

import java.util.List;

import com.yapu.archive.entity.SysDoc;
import com.yapu.archive.entity.SysDocExample;

public interface SysDocDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int countByExample(SysDocExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int deleteByExample(SysDocExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int deleteByPrimaryKey(String docid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    void insert(SysDoc record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    void insertSelective(SysDoc record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    List selectByExample(SysDocExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    SysDoc selectByPrimaryKey(String docid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByExampleSelective(SysDoc record, SysDocExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByExample(SysDoc record, SysDocExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByPrimaryKeySelective(SysDoc record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    int updateByPrimaryKey(SysDoc record);
}