package com.yapu.archive.dao.itf;

import java.util.List;

import com.yapu.archive.entity.SysTable;
import com.yapu.archive.entity.SysTableExample;

public interface SysTableDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int countByExample(SysTableExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int deleteByExample(SysTableExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int deleteByPrimaryKey(String tableid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    void insert(SysTable record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    void insertSelective(SysTable record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    List<SysTable> selectByExample(SysTableExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    SysTable selectByPrimaryKey(String tableid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int updateByExampleSelective(SysTable record, SysTableExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int updateByExample(SysTable record, SysTableExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int updateByPrimaryKeySelective(SysTable record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TABLE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    int updateByPrimaryKey(SysTable record);
}