package com.yapu.archive.dao.itf;

import java.util.List;

import com.yapu.archive.entity.SysTreeTemplet;
import com.yapu.archive.entity.SysTreeTempletExample;

public interface SysTreeTempletDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int countByExample(SysTreeTempletExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int deleteByExample(SysTreeTempletExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int deleteByPrimaryKey(String treeTempletId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    void insert(SysTreeTemplet record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    void insertSelective(SysTreeTemplet record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    List selectByExample(SysTreeTempletExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    SysTreeTemplet selectByPrimaryKey(String treeTempletId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByExampleSelective(SysTreeTemplet record, SysTreeTempletExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByExample(SysTreeTemplet record, SysTreeTempletExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByPrimaryKeySelective(SysTreeTemplet record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    int updateByPrimaryKey(SysTreeTemplet record);
}