package com.yapu.archive.entity;

import com.yapu.system.common.BaseEntity;



public class ArCollection extends BaseEntity{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_collection.COLLECTIONID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String collectionid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_collection.FILEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String fileid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_collection.TABLEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String tableid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_collection.COLLECTIONID
     *
     * @return the value of ar_collection.COLLECTIONID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_collection.COLLECTIONID
     *
     * @param collectionid the value for ar_collection.COLLECTIONID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setCollectionid(String collectionid) {
        this.collectionid = collectionid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_collection.FILEID
     *
     * @return the value of ar_collection.FILEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_collection.FILEID
     *
     * @param fileid the value for ar_collection.FILEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setFileid(String fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_collection.TABLEID
     *
     * @return the value of ar_collection.TABLEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_collection.TABLEID
     *
     * @param tableid the value for ar_collection.TABLEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }
}