package com.yapu.archive.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ArReleaseExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public ArReleaseExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    protected ArReleaseExample(ArReleaseExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table ar_release
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andReleaseidIsNull() {
            addCriterion("RELEASEID is null");
            return this;
        }

        public Criteria andReleaseidIsNotNull() {
            addCriterion("RELEASEID is not null");
            return this;
        }

        public Criteria andReleaseidEqualTo(String value) {
            addCriterion("RELEASEID =", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidNotEqualTo(String value) {
            addCriterion("RELEASEID <>", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidGreaterThan(String value) {
            addCriterion("RELEASEID >", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidGreaterThanOrEqualTo(String value) {
            addCriterion("RELEASEID >=", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidLessThan(String value) {
            addCriterion("RELEASEID <", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidLessThanOrEqualTo(String value) {
            addCriterion("RELEASEID <=", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidLike(String value) {
            addCriterion("RELEASEID like", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidNotLike(String value) {
            addCriterion("RELEASEID not like", value, "releaseid");
            return this;
        }

        public Criteria andReleaseidIn(List values) {
            addCriterion("RELEASEID in", values, "releaseid");
            return this;
        }

        public Criteria andReleaseidNotIn(List values) {
            addCriterion("RELEASEID not in", values, "releaseid");
            return this;
        }

        public Criteria andReleaseidBetween(String value1, String value2) {
            addCriterion("RELEASEID between", value1, value2, "releaseid");
            return this;
        }

        public Criteria andReleaseidNotBetween(String value1, String value2) {
            addCriterion("RELEASEID not between", value1, value2, "releaseid");
            return this;
        }

        public Criteria andFileidIsNull() {
            addCriterion("FILEID is null");
            return this;
        }

        public Criteria andFileidIsNotNull() {
            addCriterion("FILEID is not null");
            return this;
        }

        public Criteria andFileidEqualTo(String value) {
            addCriterion("FILEID =", value, "fileid");
            return this;
        }

        public Criteria andFileidNotEqualTo(String value) {
            addCriterion("FILEID <>", value, "fileid");
            return this;
        }

        public Criteria andFileidGreaterThan(String value) {
            addCriterion("FILEID >", value, "fileid");
            return this;
        }

        public Criteria andFileidGreaterThanOrEqualTo(String value) {
            addCriterion("FILEID >=", value, "fileid");
            return this;
        }

        public Criteria andFileidLessThan(String value) {
            addCriterion("FILEID <", value, "fileid");
            return this;
        }

        public Criteria andFileidLessThanOrEqualTo(String value) {
            addCriterion("FILEID <=", value, "fileid");
            return this;
        }

        public Criteria andFileidLike(String value) {
            addCriterion("FILEID like", value, "fileid");
            return this;
        }

        public Criteria andFileidNotLike(String value) {
            addCriterion("FILEID not like", value, "fileid");
            return this;
        }

        public Criteria andFileidIn(List values) {
            addCriterion("FILEID in", values, "fileid");
            return this;
        }

        public Criteria andFileidNotIn(List values) {
            addCriterion("FILEID not in", values, "fileid");
            return this;
        }

        public Criteria andFileidBetween(String value1, String value2) {
            addCriterion("FILEID between", value1, value2, "fileid");
            return this;
        }

        public Criteria andFileidNotBetween(String value1, String value2) {
            addCriterion("FILEID not between", value1, value2, "fileid");
            return this;
        }

        public Criteria andReleasemanIsNull() {
            addCriterion("RELEASEMAN is null");
            return this;
        }

        public Criteria andReleasemanIsNotNull() {
            addCriterion("RELEASEMAN is not null");
            return this;
        }

        public Criteria andReleasemanEqualTo(String value) {
            addCriterion("RELEASEMAN =", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanNotEqualTo(String value) {
            addCriterion("RELEASEMAN <>", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanGreaterThan(String value) {
            addCriterion("RELEASEMAN >", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanGreaterThanOrEqualTo(String value) {
            addCriterion("RELEASEMAN >=", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanLessThan(String value) {
            addCriterion("RELEASEMAN <", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanLessThanOrEqualTo(String value) {
            addCriterion("RELEASEMAN <=", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanLike(String value) {
            addCriterion("RELEASEMAN like", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanNotLike(String value) {
            addCriterion("RELEASEMAN not like", value, "releaseman");
            return this;
        }

        public Criteria andReleasemanIn(List values) {
            addCriterion("RELEASEMAN in", values, "releaseman");
            return this;
        }

        public Criteria andReleasemanNotIn(List values) {
            addCriterion("RELEASEMAN not in", values, "releaseman");
            return this;
        }

        public Criteria andReleasemanBetween(String value1, String value2) {
            addCriterion("RELEASEMAN between", value1, value2, "releaseman");
            return this;
        }

        public Criteria andReleasemanNotBetween(String value1, String value2) {
            addCriterion("RELEASEMAN not between", value1, value2, "releaseman");
            return this;
        }

        public Criteria andReleasedateIsNull() {
            addCriterion("RELEASEDATE is null");
            return this;
        }

        public Criteria andReleasedateIsNotNull() {
            addCriterion("RELEASEDATE is not null");
            return this;
        }

        public Criteria andReleasedateEqualTo(String value) {
            addCriterion("RELEASEDATE =", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateNotEqualTo(String value) {
            addCriterion("RELEASEDATE <>", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateGreaterThan(String value) {
            addCriterion("RELEASEDATE >", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateGreaterThanOrEqualTo(String value) {
            addCriterion("RELEASEDATE >=", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateLessThan(String value) {
            addCriterion("RELEASEDATE <", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateLessThanOrEqualTo(String value) {
            addCriterion("RELEASEDATE <=", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateLike(String value) {
            addCriterion("RELEASEDATE like", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateNotLike(String value) {
            addCriterion("RELEASEDATE not like", value, "releasedate");
            return this;
        }

        public Criteria andReleasedateIn(List values) {
            addCriterion("RELEASEDATE in", values, "releasedate");
            return this;
        }

        public Criteria andReleasedateNotIn(List values) {
            addCriterion("RELEASEDATE not in", values, "releasedate");
            return this;
        }

        public Criteria andReleasedateBetween(String value1, String value2) {
            addCriterion("RELEASEDATE between", value1, value2, "releasedate");
            return this;
        }

        public Criteria andReleasedateNotBetween(String value1, String value2) {
            addCriterion("RELEASEDATE not between", value1, value2, "releasedate");
            return this;
        }

        public Criteria andTableidIsNull() {
            addCriterion("TABLEID is null");
            return this;
        }

        public Criteria andTableidIsNotNull() {
            addCriterion("TABLEID is not null");
            return this;
        }

        public Criteria andTableidEqualTo(String value) {
            addCriterion("TABLEID =", value, "tableid");
            return this;
        }

        public Criteria andTableidNotEqualTo(String value) {
            addCriterion("TABLEID <>", value, "tableid");
            return this;
        }

        public Criteria andTableidGreaterThan(String value) {
            addCriterion("TABLEID >", value, "tableid");
            return this;
        }

        public Criteria andTableidGreaterThanOrEqualTo(String value) {
            addCriterion("TABLEID >=", value, "tableid");
            return this;
        }

        public Criteria andTableidLessThan(String value) {
            addCriterion("TABLEID <", value, "tableid");
            return this;
        }

        public Criteria andTableidLessThanOrEqualTo(String value) {
            addCriterion("TABLEID <=", value, "tableid");
            return this;
        }

        public Criteria andTableidLike(String value) {
            addCriterion("TABLEID like", value, "tableid");
            return this;
        }

        public Criteria andTableidNotLike(String value) {
            addCriterion("TABLEID not like", value, "tableid");
            return this;
        }

        public Criteria andTableidIn(List values) {
            addCriterion("TABLEID in", values, "tableid");
            return this;
        }

        public Criteria andTableidNotIn(List values) {
            addCriterion("TABLEID not in", values, "tableid");
            return this;
        }

        public Criteria andTableidBetween(String value1, String value2) {
            addCriterion("TABLEID between", value1, value2, "tableid");
            return this;
        }

        public Criteria andTableidNotBetween(String value1, String value2) {
            addCriterion("TABLEID not between", value1, value2, "tableid");
            return this;
        }
    }
}