package com.yapu.archive.entity;

import com.yapu.system.common.BaseEntity;



public class ArRelease extends BaseEntity{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_release.RELEASEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String releaseid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_release.FILEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String fileid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_release.RELEASEMAN
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String releaseman;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_release.RELEASEDATE
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String releasedate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column ar_release.TABLEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    private String tableid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_release.RELEASEID
     *
     * @return the value of ar_release.RELEASEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getReleaseid() {
        return releaseid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_release.RELEASEID
     *
     * @param releaseid the value for ar_release.RELEASEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setReleaseid(String releaseid) {
        this.releaseid = releaseid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_release.FILEID
     *
     * @return the value of ar_release.FILEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_release.FILEID
     *
     * @param fileid the value for ar_release.FILEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setFileid(String fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_release.RELEASEMAN
     *
     * @return the value of ar_release.RELEASEMAN
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getReleaseman() {
        return releaseman;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_release.RELEASEMAN
     *
     * @param releaseman the value for ar_release.RELEASEMAN
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setReleaseman(String releaseman) {
        this.releaseman = releaseman;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_release.RELEASEDATE
     *
     * @return the value of ar_release.RELEASEDATE
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_release.RELEASEDATE
     *
     * @param releasedate the value for ar_release.RELEASEDATE
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setReleasedate(String releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column ar_release.TABLEID
     *
     * @return the value of ar_release.TABLEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public String getTableid() {
        return tableid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column ar_release.TABLEID
     *
     * @param tableid the value for ar_release.TABLEID
     *
     * @ibatorgenerated Thu Nov 18 14:31:55 GMT+08:00 2010
     */
    public void setTableid(String tableid) {
        this.tableid = tableid;
    }
}