package com.yapu.archive.entity;

public class SysCode {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_CODE.CODEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String codeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_CODE.TEMPLETFIELDID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String templetfieldid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_CODE.COLUMNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String columnname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_CODE.COLUMNDATA
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String columndata;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_CODE.CODEORDER
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private Integer codeorder;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_CODE.CODEID
     *
     * @return the value of SYS_CODE.CODEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_CODE.CODEID
     *
     * @param codeid the value for SYS_CODE.CODEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setCodeid(String codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_CODE.TEMPLETFIELDID
     *
     * @return the value of SYS_CODE.TEMPLETFIELDID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getTempletfieldid() {
        return templetfieldid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_CODE.TEMPLETFIELDID
     *
     * @param templetfieldid the value for SYS_CODE.TEMPLETFIELDID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setTempletfieldid(String templetfieldid) {
        this.templetfieldid = templetfieldid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_CODE.COLUMNNAME
     *
     * @return the value of SYS_CODE.COLUMNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getColumnname() {
        return columnname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_CODE.COLUMNNAME
     *
     * @param columnname the value for SYS_CODE.COLUMNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setColumnname(String columnname) {
        this.columnname = columnname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_CODE.COLUMNDATA
     *
     * @return the value of SYS_CODE.COLUMNDATA
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getColumndata() {
        return columndata;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_CODE.COLUMNDATA
     *
     * @param columndata the value for SYS_CODE.COLUMNDATA
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setColumndata(String columndata) {
        this.columndata = columndata;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_CODE.CODEORDER
     *
     * @return the value of SYS_CODE.CODEORDER
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public Integer getCodeorder() {
        return codeorder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_CODE.CODEORDER
     *
     * @param codeorder the value for SYS_CODE.CODEORDER
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setCodeorder(Integer codeorder) {
        this.codeorder = codeorder;
    }
}