package com.yapu.archive.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SysDocExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public SysDocExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    protected SysDocExample(SysDocExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_DOC
     *
     * @ibatorgenerated Mon Nov 15 12:36:30 GMT+08:00 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andDocidIsNull() {
            addCriterion("DOCID is null");
            return this;
        }

        public Criteria andDocidIsNotNull() {
            addCriterion("DOCID is not null");
            return this;
        }

        public Criteria andDocidEqualTo(String value) {
            addCriterion("DOCID =", value, "docid");
            return this;
        }

        public Criteria andDocidNotEqualTo(String value) {
            addCriterion("DOCID <>", value, "docid");
            return this;
        }

        public Criteria andDocidGreaterThan(String value) {
            addCriterion("DOCID >", value, "docid");
            return this;
        }

        public Criteria andDocidGreaterThanOrEqualTo(String value) {
            addCriterion("DOCID >=", value, "docid");
            return this;
        }

        public Criteria andDocidLessThan(String value) {
            addCriterion("DOCID <", value, "docid");
            return this;
        }

        public Criteria andDocidLessThanOrEqualTo(String value) {
            addCriterion("DOCID <=", value, "docid");
            return this;
        }

        public Criteria andDocidLike(String value) {
            addCriterion("DOCID like", value, "docid");
            return this;
        }

        public Criteria andDocidNotLike(String value) {
            addCriterion("DOCID not like", value, "docid");
            return this;
        }

        public Criteria andDocidIn(List values) {
            addCriterion("DOCID in", values, "docid");
            return this;
        }

        public Criteria andDocidNotIn(List values) {
            addCriterion("DOCID not in", values, "docid");
            return this;
        }

        public Criteria andDocidBetween(String value1, String value2) {
            addCriterion("DOCID between", value1, value2, "docid");
            return this;
        }

        public Criteria andDocidNotBetween(String value1, String value2) {
            addCriterion("DOCID not between", value1, value2, "docid");
            return this;
        }

        public Criteria andDocserveridIsNull() {
            addCriterion("DOCSERVERID is null");
            return this;
        }

        public Criteria andDocserveridIsNotNull() {
            addCriterion("DOCSERVERID is not null");
            return this;
        }

        public Criteria andDocserveridEqualTo(String value) {
            addCriterion("DOCSERVERID =", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridNotEqualTo(String value) {
            addCriterion("DOCSERVERID <>", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridGreaterThan(String value) {
            addCriterion("DOCSERVERID >", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridGreaterThanOrEqualTo(String value) {
            addCriterion("DOCSERVERID >=", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridLessThan(String value) {
            addCriterion("DOCSERVERID <", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridLessThanOrEqualTo(String value) {
            addCriterion("DOCSERVERID <=", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridLike(String value) {
            addCriterion("DOCSERVERID like", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridNotLike(String value) {
            addCriterion("DOCSERVERID not like", value, "docserverid");
            return this;
        }

        public Criteria andDocserveridIn(List values) {
            addCriterion("DOCSERVERID in", values, "docserverid");
            return this;
        }

        public Criteria andDocserveridNotIn(List values) {
            addCriterion("DOCSERVERID not in", values, "docserverid");
            return this;
        }

        public Criteria andDocserveridBetween(String value1, String value2) {
            addCriterion("DOCSERVERID between", value1, value2, "docserverid");
            return this;
        }

        public Criteria andDocserveridNotBetween(String value1, String value2) {
            addCriterion("DOCSERVERID not between", value1, value2, "docserverid");
            return this;
        }

        public Criteria andDocoldnameIsNull() {
            addCriterion("DOCOLDNAME is null");
            return this;
        }

        public Criteria andDocoldnameIsNotNull() {
            addCriterion("DOCOLDNAME is not null");
            return this;
        }

        public Criteria andDocoldnameEqualTo(String value) {
            addCriterion("DOCOLDNAME =", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameNotEqualTo(String value) {
            addCriterion("DOCOLDNAME <>", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameGreaterThan(String value) {
            addCriterion("DOCOLDNAME >", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameGreaterThanOrEqualTo(String value) {
            addCriterion("DOCOLDNAME >=", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameLessThan(String value) {
            addCriterion("DOCOLDNAME <", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameLessThanOrEqualTo(String value) {
            addCriterion("DOCOLDNAME <=", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameLike(String value) {
            addCriterion("DOCOLDNAME like", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameNotLike(String value) {
            addCriterion("DOCOLDNAME not like", value, "docoldname");
            return this;
        }

        public Criteria andDocoldnameIn(List values) {
            addCriterion("DOCOLDNAME in", values, "docoldname");
            return this;
        }

        public Criteria andDocoldnameNotIn(List values) {
            addCriterion("DOCOLDNAME not in", values, "docoldname");
            return this;
        }

        public Criteria andDocoldnameBetween(String value1, String value2) {
            addCriterion("DOCOLDNAME between", value1, value2, "docoldname");
            return this;
        }

        public Criteria andDocoldnameNotBetween(String value1, String value2) {
            addCriterion("DOCOLDNAME not between", value1, value2, "docoldname");
            return this;
        }

        public Criteria andDocnewnameIsNull() {
            addCriterion("DOCNEWNAME is null");
            return this;
        }

        public Criteria andDocnewnameIsNotNull() {
            addCriterion("DOCNEWNAME is not null");
            return this;
        }

        public Criteria andDocnewnameEqualTo(String value) {
            addCriterion("DOCNEWNAME =", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameNotEqualTo(String value) {
            addCriterion("DOCNEWNAME <>", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameGreaterThan(String value) {
            addCriterion("DOCNEWNAME >", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameGreaterThanOrEqualTo(String value) {
            addCriterion("DOCNEWNAME >=", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameLessThan(String value) {
            addCriterion("DOCNEWNAME <", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameLessThanOrEqualTo(String value) {
            addCriterion("DOCNEWNAME <=", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameLike(String value) {
            addCriterion("DOCNEWNAME like", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameNotLike(String value) {
            addCriterion("DOCNEWNAME not like", value, "docnewname");
            return this;
        }

        public Criteria andDocnewnameIn(List values) {
            addCriterion("DOCNEWNAME in", values, "docnewname");
            return this;
        }

        public Criteria andDocnewnameNotIn(List values) {
            addCriterion("DOCNEWNAME not in", values, "docnewname");
            return this;
        }

        public Criteria andDocnewnameBetween(String value1, String value2) {
            addCriterion("DOCNEWNAME between", value1, value2, "docnewname");
            return this;
        }

        public Criteria andDocnewnameNotBetween(String value1, String value2) {
            addCriterion("DOCNEWNAME not between", value1, value2, "docnewname");
            return this;
        }

        public Criteria andDoctypeIsNull() {
            addCriterion("DOCTYPE is null");
            return this;
        }

        public Criteria andDoctypeIsNotNull() {
            addCriterion("DOCTYPE is not null");
            return this;
        }

        public Criteria andDoctypeEqualTo(String value) {
            addCriterion("DOCTYPE =", value, "doctype");
            return this;
        }

        public Criteria andDoctypeNotEqualTo(String value) {
            addCriterion("DOCTYPE <>", value, "doctype");
            return this;
        }

        public Criteria andDoctypeGreaterThan(String value) {
            addCriterion("DOCTYPE >", value, "doctype");
            return this;
        }

        public Criteria andDoctypeGreaterThanOrEqualTo(String value) {
            addCriterion("DOCTYPE >=", value, "doctype");
            return this;
        }

        public Criteria andDoctypeLessThan(String value) {
            addCriterion("DOCTYPE <", value, "doctype");
            return this;
        }

        public Criteria andDoctypeLessThanOrEqualTo(String value) {
            addCriterion("DOCTYPE <=", value, "doctype");
            return this;
        }

        public Criteria andDoctypeLike(String value) {
            addCriterion("DOCTYPE like", value, "doctype");
            return this;
        }

        public Criteria andDoctypeNotLike(String value) {
            addCriterion("DOCTYPE not like", value, "doctype");
            return this;
        }

        public Criteria andDoctypeIn(List values) {
            addCriterion("DOCTYPE in", values, "doctype");
            return this;
        }

        public Criteria andDoctypeNotIn(List values) {
            addCriterion("DOCTYPE not in", values, "doctype");
            return this;
        }

        public Criteria andDoctypeBetween(String value1, String value2) {
            addCriterion("DOCTYPE between", value1, value2, "doctype");
            return this;
        }

        public Criteria andDoctypeNotBetween(String value1, String value2) {
            addCriterion("DOCTYPE not between", value1, value2, "doctype");
            return this;
        }
        
        public Criteria andDocextIsNull() {
            addCriterion("DOCEXT is null");
            return this;
        }

        public Criteria andDocextIsNotNull() {
            addCriterion("DOCEXT is not null");
            return this;
        }

        public Criteria andDocextEqualTo(String value) {
            addCriterion("DOCEXT =", value, "docext");
            return this;
        }

        public Criteria andDocDocextNotEqualTo(String value) {
            addCriterion("DOCEXT <>", value, "docext");
            return this;
        }

        public Criteria andDocextGreaterThan(String value) {
            addCriterion("DOCEXT >", value, "docext");
            return this;
        }

        public Criteria andDocextGreaterThanOrEqualTo(String value) {
            addCriterion("DOCEXT >=", value, "docext");
            return this;
        }

        public Criteria andDocextLessThan(String value) {
            addCriterion("DOCEXT <", value, "docext");
            return this;
        }

        public Criteria andDocextLessThanOrEqualTo(String value) {
            addCriterion("DOCEXT <=", value, "docext");
            return this;
        }

        public Criteria andDocextLike(String value) {
            addCriterion("DOCEXT like", value, "docext");
            return this;
        }

        public Criteria andDocextNotLike(String value) {
            addCriterion("DOCEXT not like", value, "docext");
            return this;
        }

        public Criteria andDocextIn(List values) {
            addCriterion("DOCEXT in", values, "docext");
            return this;
        }

        public Criteria andDocextNotIn(List values) {
            addCriterion("DOCEXT not in", values, "docext");
            return this;
        }

        public Criteria andDocextBetween(String value1, String value2) {
            addCriterion("DOCEXT between", value1, value2, "docext");
            return this;
        }

        public Criteria andDocextNotBetween(String value1, String value2) {
            addCriterion("DOCEXT not between", value1, value2, "docext");
            return this;
        }

        public Criteria andDoclengthIsNull() {
            addCriterion("DOCLENGTH is null");
            return this;
        }

        public Criteria andDoclengthIsNotNull() {
            addCriterion("DOCLENGTH is not null");
            return this;
        }

        public Criteria andDoclengthEqualTo(String value) {
            addCriterion("DOCLENGTH =", value, "doclength");
            return this;
        }

        public Criteria andDoclengthNotEqualTo(String value) {
            addCriterion("DOCLENGTH <>", value, "doclength");
            return this;
        }

        public Criteria andDoclengthGreaterThan(String value) {
            addCriterion("DOCLENGTH >", value, "doclength");
            return this;
        }

        public Criteria andDoclengthGreaterThanOrEqualTo(String value) {
            addCriterion("DOCLENGTH >=", value, "doclength");
            return this;
        }

        public Criteria andDoclengthLessThan(String value) {
            addCriterion("DOCLENGTH <", value, "doclength");
            return this;
        }

        public Criteria andDoclengthLessThanOrEqualTo(String value) {
            addCriterion("DOCLENGTH <=", value, "doclength");
            return this;
        }

        public Criteria andDoclengthLike(String value) {
            addCriterion("DOCLENGTH like", value, "doclength");
            return this;
        }

        public Criteria andDoclengthNotLike(String value) {
            addCriterion("DOCLENGTH not like", value, "doclength");
            return this;
        }

        public Criteria andDoclengthIn(List values) {
            addCriterion("DOCLENGTH in", values, "doclength");
            return this;
        }

        public Criteria andDoclengthNotIn(List values) {
            addCriterion("DOCLENGTH not in", values, "doclength");
            return this;
        }

        public Criteria andDoclengthBetween(String value1, String value2) {
            addCriterion("DOCLENGTH between", value1, value2, "doclength");
            return this;
        }

        public Criteria andDoclengthNotBetween(String value1, String value2) {
            addCriterion("DOCLENGTH not between", value1, value2, "doclength");
            return this;
        }

        public Criteria andDocpathIsNull() {
            addCriterion("DOCPATH is null");
            return this;
        }

        public Criteria andDocpathIsNotNull() {
            addCriterion("DOCPATH is not null");
            return this;
        }

        public Criteria andDocpathEqualTo(String value) {
            addCriterion("DOCPATH =", value, "docpath");
            return this;
        }

        public Criteria andDocpathNotEqualTo(String value) {
            addCriterion("DOCPATH <>", value, "docpath");
            return this;
        }

        public Criteria andDocpathGreaterThan(String value) {
            addCriterion("DOCPATH >", value, "docpath");
            return this;
        }

        public Criteria andDocpathGreaterThanOrEqualTo(String value) {
            addCriterion("DOCPATH >=", value, "docpath");
            return this;
        }

        public Criteria andDocpathLessThan(String value) {
            addCriterion("DOCPATH <", value, "docpath");
            return this;
        }

        public Criteria andDocpathLessThanOrEqualTo(String value) {
            addCriterion("DOCPATH <=", value, "docpath");
            return this;
        }

        public Criteria andDocpathLike(String value) {
            addCriterion("DOCPATH like", value, "docpath");
            return this;
        }

        public Criteria andDocpathNotLike(String value) {
            addCriterion("DOCPATH not like", value, "docpath");
            return this;
        }

        public Criteria andDocpathIn(List values) {
            addCriterion("DOCPATH in", values, "docpath");
            return this;
        }

        public Criteria andDocpathNotIn(List values) {
            addCriterion("DOCPATH not in", values, "docpath");
            return this;
        }

        public Criteria andDocpathBetween(String value1, String value2) {
            addCriterion("DOCPATH between", value1, value2, "docpath");
            return this;
        }

        public Criteria andDocpathNotBetween(String value1, String value2) {
            addCriterion("DOCPATH not between", value1, value2, "docpath");
            return this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("CREATER is null");
            return this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("CREATER is not null");
            return this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("CREATER =", value, "creater");
            return this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("CREATER <>", value, "creater");
            return this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("CREATER >", value, "creater");
            return this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("CREATER >=", value, "creater");
            return this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("CREATER <", value, "creater");
            return this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("CREATER <=", value, "creater");
            return this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("CREATER like", value, "creater");
            return this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("CREATER not like", value, "creater");
            return this;
        }

        public Criteria andCreaterIn(List values) {
            addCriterion("CREATER in", values, "creater");
            return this;
        }

        public Criteria andCreaterNotIn(List values) {
            addCriterion("CREATER not in", values, "creater");
            return this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("CREATER between", value1, value2, "creater");
            return this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("CREATER not between", value1, value2, "creater");
            return this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return this;
        }

        public Criteria andCreatetimeEqualTo(String value) {
            addCriterion("CREATETIME =", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotEqualTo(String value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeGreaterThan(String value) {
            addCriterion("CREATETIME >", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeLessThan(String value) {
            addCriterion("CREATETIME <", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(String value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeLike(String value) {
            addCriterion("CREATETIME like", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotLike(String value) {
            addCriterion("CREATETIME not like", value, "createtime");
            return this;
        }

        public Criteria andCreatetimeIn(List values) {
            addCriterion("CREATETIME in", values, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotIn(List values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return this;
        }

        public Criteria andCreatetimeBetween(String value1, String value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return this;
        }

        public Criteria andCreatetimeNotBetween(String value1, String value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return this;
        }

        public Criteria andFileidIsNull() {
            addCriterion("FILEID is null");
            return this;
        }

        public Criteria andFileidIsNotNull() {
            addCriterion("FILEID is not null");
            return this;
        }

        public Criteria andFileidEqualTo(String value) {
            addCriterion("FILEID =", value, "fileid");
            return this;
        }

        public Criteria andFileidNotEqualTo(String value) {
            addCriterion("FILEID <>", value, "fileid");
            return this;
        }

        public Criteria andFileidGreaterThan(String value) {
            addCriterion("FILEID >", value, "fileid");
            return this;
        }

        public Criteria andFileidGreaterThanOrEqualTo(String value) {
            addCriterion("FILEID >=", value, "fileid");
            return this;
        }

        public Criteria andFileidLessThan(String value) {
            addCriterion("FILEID <", value, "fileid");
            return this;
        }

        public Criteria andFileidLessThanOrEqualTo(String value) {
            addCriterion("FILEID <=", value, "fileid");
            return this;
        }

        public Criteria andFileidLike(String value) {
            addCriterion("FILEID like", value, "fileid");
            return this;
        }

        public Criteria andFileidNotLike(String value) {
            addCriterion("FILEID not like", value, "fileid");
            return this;
        }

        public Criteria andFileidIn(List values) {
            addCriterion("FILEID in", values, "fileid");
            return this;
        }

        public Criteria andFileidNotIn(List values) {
            addCriterion("FILEID not in", values, "fileid");
            return this;
        }

        public Criteria andFileidBetween(String value1, String value2) {
            addCriterion("FILEID between", value1, value2, "fileid");
            return this;
        }

        public Criteria andFileidNotBetween(String value1, String value2) {
            addCriterion("FILEID not between", value1, value2, "fileid");
            return this;
        }

        public Criteria andTableidIsNull() {
            addCriterion("TABLEID is null");
            return this;
        }

        public Criteria andTableidIsNotNull() {
            addCriterion("TABLEID is not null");
            return this;
        }

        public Criteria andTableidEqualTo(String value) {
            addCriterion("TABLEID =", value, "tableid");
            return this;
        }

        public Criteria andTableidNotEqualTo(String value) {
            addCriterion("TABLEID <>", value, "tableid");
            return this;
        }

        public Criteria andTableidGreaterThan(String value) {
            addCriterion("TABLEID >", value, "tableid");
            return this;
        }

        public Criteria andTableidGreaterThanOrEqualTo(String value) {
            addCriterion("TABLEID >=", value, "tableid");
            return this;
        }

        public Criteria andTableidLessThan(String value) {
            addCriterion("TABLEID <", value, "tableid");
            return this;
        }

        public Criteria andTableidLessThanOrEqualTo(String value) {
            addCriterion("TABLEID <=", value, "tableid");
            return this;
        }

        public Criteria andTableidLike(String value) {
            addCriterion("TABLEID like", value, "tableid");
            return this;
        }

        public Criteria andTableidNotLike(String value) {
            addCriterion("TABLEID not like", value, "tableid");
            return this;
        }

        public Criteria andTableidIn(List values) {
            addCriterion("TABLEID in", values, "tableid");
            return this;
        }

        public Criteria andTableidNotIn(List values) {
            addCriterion("TABLEID not in", values, "tableid");
            return this;
        }

        public Criteria andTableidBetween(String value1, String value2) {
            addCriterion("TABLEID between", value1, value2, "tableid");
            return this;
        }

        public Criteria andTableidNotBetween(String value1, String value2) {
            addCriterion("TABLEID not between", value1, value2, "tableid");
            return this;
        }
        
        public Criteria andTreeidIsNull() {
            addCriterion("TREEID is null");
            return this;
        }

        public Criteria andTreeidIsNotNull() {
            addCriterion("TREEID is not null");
            return this;
        }

        public Criteria andTreeidEqualTo(String value) {
            addCriterion("TREEID =", value, "treeid");
            return this;
        }

        public Criteria andTreeidNotEqualTo(String value) {
            addCriterion("TREEID <>", value, "treeid");
            return this;
        }

        public Criteria andTreeidGreaterThan(String value) {
            addCriterion("TREEID >", value, "treeid");
            return this;
        }

        public Criteria andTreeidGreaterThanOrEqualTo(String value) {
            addCriterion("TREEID >=", value, "treeid");
            return this;
        }

        public Criteria andTreeidLessThan(String value) {
            addCriterion("TREEID <", value, "treeid");
            return this;
        }

        public Criteria andTreeidLessThanOrEqualTo(String value) {
            addCriterion("TREEID <=", value, "treeid");
            return this;
        }

        public Criteria andTreeidLike(String value) {
            addCriterion("TREEID like", value, "treeid");
            return this;
        }

        public Criteria andTreeidNotLike(String value) {
            addCriterion("TREEID not like", value, "treeid");
            return this;
        }

        public Criteria andTreeidIn(List values) {
            addCriterion("TREEID in", values, "treeid");
            return this;
        }

        public Criteria andTreeidNotIn(List values) {
            addCriterion("TREEID not in", values, "treeid");
            return this;
        }

        public Criteria andTreeidBetween(String value1, String value2) {
            addCriterion("TREEID between", value1, value2, "treeid");
            return this;
        }

        public Criteria andTreeidNotBetween(String value1, String value2) {
            addCriterion("TREEID not between", value1, value2, "treeid");
            return this;
        }

        public Criteria andAuthorityIsNull() {
            addCriterion("AUTHORITY is null");
            return this;
        }

        public Criteria andAuthorityIsNotNull() {
            addCriterion("AUTHORITY is not null");
            return this;
        }

        public Criteria andAuthorityEqualTo(String value) {
            addCriterion("AUTHORITY =", value, "authority");
            return this;
        }

        public Criteria andAuthorityNotEqualTo(String value) {
            addCriterion("AUTHORITY <>", value, "authority");
            return this;
        }

        public Criteria andAuthorityGreaterThan(String value) {
            addCriterion("AUTHORITY >", value, "authority");
            return this;
        }

        public Criteria andAuthorityGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHORITY >=", value, "authority");
            return this;
        }

        public Criteria andAuthorityLessThan(String value) {
            addCriterion("AUTHORITY <", value, "authority");
            return this;
        }

        public Criteria andAuthorityLessThanOrEqualTo(String value) {
            addCriterion("AUTHORITY <=", value, "authority");
            return this;
        }

        public Criteria andAuthorityLike(String value) {
            addCriterion("AUTHORITY like", value, "authority");
            return this;
        }

        public Criteria andAuthorityNotLike(String value) {
            addCriterion("AUTHORITY not like", value, "authority");
            return this;
        }

        public Criteria andAuthorityIn(List values) {
            addCriterion("AUTHORITY in", values, "authority");
            return this;
        }

        public Criteria andAuthorityNotIn(List values) {
            addCriterion("AUTHORITY not in", values, "authority");
            return this;
        }

        public Criteria andAuthorityBetween(String value1, String value2) {
            addCriterion("AUTHORITY between", value1, value2, "authority");
            return this;
        }

        public Criteria andAuthorityNotBetween(String value1, String value2) {
            addCriterion("AUTHORITY not between", value1, value2, "authority");
            return this;
        }
        public Criteria andHeightIsNull() {
            addCriterion("HEIGHT is null");
            return this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("HEIGHT is not null");
            return this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("HEIGHT =", value, "height");
            return this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("HEIGHT <>", value, "height");
            return this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("HEIGHT >", value, "height");
            return this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("HEIGHT >=", value, "height");
            return this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("HEIGHT <", value, "height");
            return this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("HEIGHT <=", value, "height");
            return this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("HEIGHT like", value, "height");
            return this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("HEIGHT not like", value, "height");
            return this;
        }

        public Criteria andHeightIn(List values) {
            addCriterion("HEIGHT in", values, "height");
            return this;
        }

        public Criteria andHeightNotIn(List values) {
            addCriterion("HEIGHT not in", values, "height");
            return this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("HEIGHT between", value1, value2, "height");
            return this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("HEIGHT not between", value1, value2, "height");
            return this;
        }
        public Criteria andWidthIsNull() {
            addCriterion("WIDTH is null");
            return this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("WIDTH is not null");
            return this;
        }

        public Criteria andWidthEqualTo(String value) {
            addCriterion("WIDTH =", value, "width");
            return this;
        }

        public Criteria andWidthNotEqualTo(String value) {
            addCriterion("WIDTH <>", value, "width");
            return this;
        }

        public Criteria andWidthGreaterThan(String value) {
            addCriterion("WIDTH >", value, "width");
            return this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(String value) {
            addCriterion("WIDTH >=", value, "width");
            return this;
        }

        public Criteria andWidthLessThan(String value) {
            addCriterion("WIDTH <", value, "width");
            return this;
        }

        public Criteria andWidthLessThanOrEqualTo(String value) {
            addCriterion("WIDTH <=", value, "width");
            return this;
        }

        public Criteria andWidthLike(String value) {
            addCriterion("WIDTH like", value, "width");
            return this;
        }

        public Criteria andWidthNotLike(String value) {
            addCriterion("WIDTH not like", value, "width");
            return this;
        }

        public Criteria andWidthIn(List values) {
            addCriterion("WIDTH in", values, "width");
            return this;
        }

        public Criteria andWidthNotIn(List values) {
            addCriterion("WIDTH not in", values, "width");
            return this;
        }

        public Criteria andWidthBetween(String value1, String value2) {
            addCriterion("WIDTH between", value1, value2, "width");
            return this;
        }

        public Criteria andWidthNotBetween(String value1, String value2) {
            addCriterion("WIDTH not between", value1, value2, "width");
            return this;
        }
        public Criteria andHiddenIsNull() {
            addCriterion("HIDDEN is null");
            return this;
        }

        public Criteria andHiddenIsNotNull() {
            addCriterion("HIDDEN is not null");
            return this;
        }

        public Criteria andHiddenEqualTo(String value) {
            addCriterion("HIDDEN =", value, "hidden");
            return this;
        }

        public Criteria andHiddenNotEqualTo(String value) {
            addCriterion("HIDDEN <>", value, "hidden");
            return this;
        }

        public Criteria andHiddenGreaterThan(String value) {
            addCriterion("HIDDEN >", value, "hidden");
            return this;
        }

        public Criteria andHiddenGreaterThanOrEqualTo(String value) {
            addCriterion("HIDDEN >=", value, "hidden");
            return this;
        }

        public Criteria andHiddenLessThan(String value) {
            addCriterion("HIDDEN <", value, "hidden");
            return this;
        }

        public Criteria andHiddenLessThanOrEqualTo(String value) {
            addCriterion("HIDDEN <=", value, "hidden");
            return this;
        }

        public Criteria andHiddenLike(String value) {
            addCriterion("HIDDEN like", value, "hidden");
            return this;
        }

        public Criteria andHiddenNotLike(String value) {
            addCriterion("HIDDEN not like", value, "hidden");
            return this;
        }

        public Criteria andHiddenIn(List values) {
            addCriterion("HIDDEN in", values, "hidden");
            return this;
        }

        public Criteria andHiddenNotIn(List values) {
            addCriterion("HIDDEN not in", values, "hidden");
            return this;
        }

        public Criteria andHiddenBetween(String value1, String value2) {
            addCriterion("HIDDEN between", value1, value2, "hidden");
            return this;
        }

        public Criteria andHiddenNotBetween(String value1, String value2) {
            addCriterion("HIDDEN not between", value1, value2, "hidden");
            return this;
        }
        public Criteria andLockedIsNull() {
            addCriterion("LOCKED is null");
            return this;
        }

        public Criteria andLockedIsNotNull() {
            addCriterion("LOCKED is not null");
            return this;
        }

        public Criteria andLockedEqualTo(String value) {
            addCriterion("LOCKED =", value, "locked");
            return this;
        }

        public Criteria andLockedNotEqualTo(String value) {
            addCriterion("LOCKED <>", value, "locked");
            return this;
        }

        public Criteria andLockedGreaterThan(String value) {
            addCriterion("LOCKED >", value, "locked");
            return this;
        }

        public Criteria andLockedGreaterThanOrEqualTo(String value) {
            addCriterion("LOCKED >=", value, "locked");
            return this;
        }

        public Criteria andLockedLessThan(String value) {
            addCriterion("LOCKED <", value, "locked");
            return this;
        }

        public Criteria andLockedLessThanOrEqualTo(String value) {
            addCriterion("LOCKED <=", value, "locked");
            return this;
        }

        public Criteria andLockedLike(String value) {
            addCriterion("LOCKED like", value, "locked");
            return this;
        }

        public Criteria andLockedNotLike(String value) {
            addCriterion("LOCKED not like", value, "locked");
            return this;
        }

        public Criteria andLockedIn(List values) {
            addCriterion("LOCKED in", values, "locked");
            return this;
        }

        public Criteria andLockedNotIn(List values) {
            addCriterion("LOCKED not in", values, "locked");
            return this;
        }

        public Criteria andLockedBetween(String value1, String value2) {
            addCriterion("LOCKED between", value1, value2, "locked");
            return this;
        }

        public Criteria andLockedNotBetween(String value1, String value2) {
            addCriterion("LOCKED not between", value1, value2, "locked");
            return this;
        }
        public Criteria andWriteIsNull() {
            addCriterion("MWRITE is null");
            return this;
        }

        public Criteria andWriteIsNotNull() {
            addCriterion("MWRITE is not null");
            return this;
        }

        public Criteria andWriteEqualTo(String value) {
            addCriterion("MWRITE =", value, "mwrite");
            return this;
        }

        public Criteria andWriteNotEqualTo(String value) {
            addCriterion("MWRITE <>", value, "mwrite");
            return this;
        }

        public Criteria andWriteGreaterThan(String value) {
            addCriterion("MWRITE >", value, "mwrite");
            return this;
        }

        public Criteria andWriteGreaterThanOrEqualTo(String value) {
            addCriterion("MWRITE >=", value, "mwrite");
            return this;
        }

        public Criteria andWriteLessThan(String value) {
            addCriterion("MWRITE <", value, "mwrite");
            return this;
        }

        public Criteria andWriteLessThanOrEqualTo(String value) {
            addCriterion("MWRITE <=", value, "mwrite");
            return this;
        }

        public Criteria andWriteLike(String value) {
            addCriterion("MWRITE like", value, "mwrite");
            return this;
        }

        public Criteria andWriteNotLike(String value) {
            addCriterion("MWRITE not like", value, "mwrite");
            return this;
        }

        public Criteria andWriteIn(List values) {
            addCriterion("MWRITE in", values, "mwrite");
            return this;
        }

        public Criteria andWriteNotIn(List values) {
            addCriterion("MWRITE not in", values, "mwrite");
            return this;
        }

        public Criteria andWriteBetween(String value1, String value2) {
            addCriterion("MWRITE between", value1, value2, "mwrite");
            return this;
        }

        public Criteria andWriteNotBetween(String value1, String value2) {
            addCriterion("MWRITE not between", value1, value2, "mwrite");
            return this;
        }
        public Criteria andMreadIsNull() {
            addCriterion("MREAD is null");
            return this;
        }

        public Criteria andMreadIsNotNull() {
            addCriterion("MREAD is not null");
            return this;
        }

        public Criteria andMreadEqualTo(String value) {
            addCriterion("MREAD =", value, "mread");
            return this;
        }

        public Criteria andMreadNotEqualTo(String value) {
            addCriterion("MREAD <>", value, "mread");
            return this;
        }

        public Criteria andMreadGreaterThan(String value) {
            addCriterion("MREAD >", value, "mread");
            return this;
        }

        public Criteria andMreadGreaterThanOrEqualTo(String value) {
            addCriterion("MREAD >=", value, "mread");
            return this;
        }

        public Criteria andMreadLessThan(String value) {
            addCriterion("MREAD <", value, "mread");
            return this;
        }

        public Criteria andMreadLessThanOrEqualTo(String value) {
            addCriterion("MREAD <=", value, "mread");
            return this;
        }

        public Criteria andMreadLike(String value) {
            addCriterion("MREAD like", value, "mread");
            return this;
        }

        public Criteria andMreadNotLike(String value) {
            addCriterion("MREAD not like", value, "mread");
            return this;
        }

        public Criteria andMreadIn(List values) {
            addCriterion("MREAD in", values, "mread");
            return this;
        }

        public Criteria andMreadNotIn(List values) {
            addCriterion("MREAD not in", values, "mread");
            return this;
        }

        public Criteria andMreadBetween(String value1, String value2) {
            addCriterion("MREAD between", value1, value2, "mread");
            return this;
        }

        public Criteria andMreadNotBetween(String value1, String value2) {
            addCriterion("MREAD not between", value1, value2, "mread");
            return this;
        }
        public Criteria andMimeIsNull() {
            addCriterion("MIME is null");
            return this;
        }

        public Criteria andMimeIsNotNull() {
            addCriterion("MIME is not null");
            return this;
        }

        public Criteria andMimeEqualTo(String value) {
            addCriterion("MIME =", value, "mime");
            return this;
        }

        public Criteria andMimeNotEqualTo(String value) {
            addCriterion("MIME <>", value, "mime");
            return this;
        }

        public Criteria andMimeGreaterThan(String value) {
            addCriterion("MIME >", value, "mime");
            return this;
        }

        public Criteria andMimeGreaterThanOrEqualTo(String value) {
            addCriterion("MIME >=", value, "mime");
            return this;
        }

        public Criteria andMimeLessThan(String value) {
            addCriterion("MIME <", value, "mime");
            return this;
        }

        public Criteria andMimeLessThanOrEqualTo(String value) {
            addCriterion("MIME <=", value, "mime");
            return this;
        }

        public Criteria andMimeLike(String value) {
            addCriterion("MIME like", value, "mime");
            return this;
        }

        public Criteria andMimeNotLike(String value) {
            addCriterion("MIME not like", value, "mime");
            return this;
        }

        public Criteria andMimeIn(List values) {
            addCriterion("MIME in", values, "mime");
            return this;
        }

        public Criteria andMimeNotIn(List values) {
            addCriterion("MIME not in", values, "mime");
            return this;
        }

        public Criteria andMimeBetween(String value1, String value2) {
            addCriterion("MIME between", value1, value2, "mime");
            return this;
        }

        public Criteria andMimeNotBetween(String value1, String value2) {
            addCriterion("MIME not between", value1, value2, "mime");
            return this;
        }
        public Criteria andMtimeIsNull() {
            addCriterion("MTIME is null");
            return this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("MTIME is not null");
            return this;
        }

        public Criteria andMtimeEqualTo(String value) {
            addCriterion("MTIME =", value, "mtime");
            return this;
        }

        public Criteria andMtimeNotEqualTo(String value) {
            addCriterion("MTIME <>", value, "mtime");
            return this;
        }

        public Criteria andMtimeGreaterThan(String value) {
            addCriterion("MTIME >", value, "mtime");
            return this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(String value) {
            addCriterion("MTIME >=", value, "mtime");
            return this;
        }

        public Criteria andMtimeLessThan(String value) {
            addCriterion("MTIME <", value, "mtime");
            return this;
        }

        public Criteria andMtimeLessThanOrEqualTo(String value) {
            addCriterion("MTIME <=", value, "mtime");
            return this;
        }

        public Criteria andMtimeLike(String value) {
            addCriterion("MTIME like", value, "mtime");
            return this;
        }

        public Criteria andMtimeNotLike(String value) {
            addCriterion("MTIME not like", value, "mtime");
            return this;
        }

        public Criteria andMtimeIn(List values) {
            addCriterion("MTIME in", values, "mtime");
            return this;
        }

        public Criteria andMtimeNotIn(List values) {
            addCriterion("MTIME not in", values, "mtime");
            return this;
        }

        public Criteria andMtimeBetween(String value1, String value2) {
            addCriterion("MTIME between", value1, value2, "mtime");
            return this;
        }

        public Criteria andMtimeNotBetween(String value1, String value2) {
            addCriterion("MTIME not between", value1, value2, "mtime");
            return this;
        }
        public Criteria andParentidIsNull() {
            addCriterion("PARENTID is null");
            return this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("PARENTID is not null");
            return this;
        }

        public Criteria andParentidEqualTo(String value) {
            addCriterion("PARENTID =", value, "parentid");
            return this;
        }

        public Criteria andParentidNotEqualTo(String value) {
            addCriterion("PARENTID <>", value, "parentid");
            return this;
        }

        public Criteria andParentidGreaterThan(String value) {
            addCriterion("PARENTID >", value, "parentid");
            return this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTID >=", value, "parentid");
            return this;
        }

        public Criteria andParentidLessThan(String value) {
            addCriterion("PARENTID <", value, "parentid");
            return this;
        }

        public Criteria andParentidLessThanOrEqualTo(String value) {
            addCriterion("PARENTID <=", value, "parentid");
            return this;
        }

        public Criteria andParentidLike(String value) {
            addCriterion("PARENTID like", value, "parentid");
            return this;
        }

        public Criteria andParentidNotLike(String value) {
            addCriterion("PARENTID not like", value, "parentid");
            return this;
        }

        public Criteria andParentidIn(List values) {
            addCriterion("PARENTID in", values, "parentid");
            return this;
        }

        public Criteria andParentidNotIn(List values) {
            addCriterion("PARENTID not in", values, "parentid");
            return this;
        }

        public Criteria andParentidBetween(String value1, String value2) {
            addCriterion("PARENTID between", value1, value2, "parentid");
            return this;
        }

        public Criteria andParentidNotBetween(String value1, String value2) {
            addCriterion("PARENTID not between", value1, value2, "parentid");
            return this;
        }
    }
}