package com.yapu.archive.entity;

public class SysOrgTree {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_TREE.ORG_TREE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String orgTreeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_TREE.ORGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String orgid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_TREE.TREEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String treeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_TREE.FILESCAN
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private Integer filescan;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_TREE.FILEDOWN
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private Integer filedown;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_TREE.FILEPRINT
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private Integer fileprint;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_TREE.ORG_TREE_ID
     *
     * @return the value of SYS_ORG_TREE.ORG_TREE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOrgTreeId() {
        return orgTreeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_TREE.ORG_TREE_ID
     *
     * @param orgTreeId the value for SYS_ORG_TREE.ORG_TREE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOrgTreeId(String orgTreeId) {
        this.orgTreeId = orgTreeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_TREE.ORGID
     *
     * @return the value of SYS_ORG_TREE.ORGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_TREE.ORGID
     *
     * @param orgid the value for SYS_ORG_TREE.ORGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_TREE.TREEID
     *
     * @return the value of SYS_ORG_TREE.TREEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getTreeid() {
        return treeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_TREE.TREEID
     *
     * @param treeid the value for SYS_ORG_TREE.TREEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setTreeid(String treeid) {
        this.treeid = treeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_TREE.FILESCAN
     *
     * @return the value of SYS_ORG_TREE.FILESCAN
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public Integer getFilescan() {
        return filescan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_TREE.FILESCAN
     *
     * @param filescan the value for SYS_ORG_TREE.FILESCAN
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setFilescan(Integer filescan) {
        this.filescan = filescan;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_TREE.FILEDOWN
     *
     * @return the value of SYS_ORG_TREE.FILEDOWN
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public Integer getFiledown() {
        return filedown;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_TREE.FILEDOWN
     *
     * @param filedown the value for SYS_ORG_TREE.FILEDOWN
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setFiledown(Integer filedown) {
        this.filedown = filedown;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_TREE.FILEPRINT
     *
     * @return the value of SYS_ORG_TREE.FILEPRINT
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public Integer getFileprint() {
        return fileprint;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_TREE.FILEPRINT
     *
     * @param fileprint the value for SYS_ORG_TREE.FILEPRINT
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setFileprint(Integer fileprint) {
        this.fileprint = fileprint;
    }
}