package com.yapu.archive.entity;

public class SysTree {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE.TREEID
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    private String treeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE.PARENTID
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    private String parentid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE.TREENAME
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    private String treename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE.TREETYPE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    private String treetype;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE.TREENODE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    private String treenode;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE.TREEID
     *
     * @return the value of SYS_TREE.TREEID
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public String getTreeid() {
        return treeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE.TREEID
     *
     * @param treeid the value for SYS_TREE.TREEID
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void setTreeid(String treeid) {
        this.treeid = treeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE.PARENTID
     *
     * @return the value of SYS_TREE.PARENTID
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE.PARENTID
     *
     * @param parentid the value for SYS_TREE.PARENTID
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE.TREENAME
     *
     * @return the value of SYS_TREE.TREENAME
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public String getTreename() {
        return treename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE.TREENAME
     *
     * @param treename the value for SYS_TREE.TREENAME
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void setTreename(String treename) {
        this.treename = treename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE.TREETYPE
     *
     * @return the value of SYS_TREE.TREETYPE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public String getTreetype() {
        return treetype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE.TREETYPE
     *
     * @param treetype the value for SYS_TREE.TREETYPE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void setTreetype(String treetype) {
        this.treetype = treetype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE.TREENODE
     *
     * @return the value of SYS_TREE.TREENODE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public String getTreenode() {
        return treenode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE.TREENODE
     *
     * @param treenode the value for SYS_TREE.TREENODE
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void setTreenode(String treenode) {
        this.treenode = treenode;
    }
}