package com.yapu.archive.entity;

public class SysTreeTemplet {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE_TEMPLET.TREE_TEMPLET_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String treeTempletId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE_TEMPLET.TREEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String treeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TREE_TEMPLET.TEMPLETID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String templetid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE_TEMPLET.TREE_TEMPLET_ID
     *
     * @return the value of SYS_TREE_TEMPLET.TREE_TEMPLET_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getTreeTempletId() {
        return treeTempletId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE_TEMPLET.TREE_TEMPLET_ID
     *
     * @param treeTempletId the value for SYS_TREE_TEMPLET.TREE_TEMPLET_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setTreeTempletId(String treeTempletId) {
        this.treeTempletId = treeTempletId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE_TEMPLET.TREEID
     *
     * @return the value of SYS_TREE_TEMPLET.TREEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getTreeid() {
        return treeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE_TEMPLET.TREEID
     *
     * @param treeid the value for SYS_TREE_TEMPLET.TREEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setTreeid(String treeid) {
        this.treeid = treeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TREE_TEMPLET.TEMPLETID
     *
     * @return the value of SYS_TREE_TEMPLET.TEMPLETID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getTempletid() {
        return templetid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TREE_TEMPLET.TEMPLETID
     *
     * @param templetid the value for SYS_TREE_TEMPLET.TEMPLETID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setTempletid(String templetid) {
        this.templetid = templetid;
    }
}