package com.yapu.archive.entity;

public class SysTemplet {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TEMPLET.TEMPLETID
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    private String templetid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TEMPLET.TEMPLETNAME
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    private String templetname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_TEMPLET.TEMPLETTYPE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    private String templettype;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TEMPLET.TEMPLETID
     *
     * @return the value of SYS_TEMPLET.TEMPLETID
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public String getTempletid() {
        return templetid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TEMPLET.TEMPLETID
     *
     * @param templetid the value for SYS_TEMPLET.TEMPLETID
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public void setTempletid(String templetid) {
        this.templetid = templetid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TEMPLET.TEMPLETNAME
     *
     * @return the value of SYS_TEMPLET.TEMPLETNAME
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public String getTempletname() {
        return templetname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TEMPLET.TEMPLETNAME
     *
     * @param templetname the value for SYS_TEMPLET.TEMPLETNAME
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public void setTempletname(String templetname) {
        this.templetname = templetname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_TEMPLET.TEMPLETTYPE
     *
     * @return the value of SYS_TEMPLET.TEMPLETTYPE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public String getTemplettype() {
        return templettype;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_TEMPLET.TEMPLETTYPE
     *
     * @param templettype the value for SYS_TEMPLET.TEMPLETTYPE
     *
     * @ibatorgenerated Sun Nov 14 02:07:28 GMT+08:00 2010
     */
    public void setTemplettype(String templettype) {
        this.templettype = templettype;
    }
}