package com.yapu.archive.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SysTreeTempletExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysTreeTempletExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    protected SysTreeTempletExample(SysTreeTempletExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_TREE_TEMPLET
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andTreeTempletIdIsNull() {
            addCriterion("TREE_TEMPLET_ID is null");
            return this;
        }

        public Criteria andTreeTempletIdIsNotNull() {
            addCriterion("TREE_TEMPLET_ID is not null");
            return this;
        }

        public Criteria andTreeTempletIdEqualTo(String value) {
            addCriterion("TREE_TEMPLET_ID =", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdNotEqualTo(String value) {
            addCriterion("TREE_TEMPLET_ID <>", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdGreaterThan(String value) {
            addCriterion("TREE_TEMPLET_ID >", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdGreaterThanOrEqualTo(String value) {
            addCriterion("TREE_TEMPLET_ID >=", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdLessThan(String value) {
            addCriterion("TREE_TEMPLET_ID <", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdLessThanOrEqualTo(String value) {
            addCriterion("TREE_TEMPLET_ID <=", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdLike(String value) {
            addCriterion("TREE_TEMPLET_ID like", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdNotLike(String value) {
            addCriterion("TREE_TEMPLET_ID not like", value, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdIn(List values) {
            addCriterion("TREE_TEMPLET_ID in", values, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdNotIn(List values) {
            addCriterion("TREE_TEMPLET_ID not in", values, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdBetween(String value1, String value2) {
            addCriterion("TREE_TEMPLET_ID between", value1, value2, "treeTempletId");
            return this;
        }

        public Criteria andTreeTempletIdNotBetween(String value1, String value2) {
            addCriterion("TREE_TEMPLET_ID not between", value1, value2, "treeTempletId");
            return this;
        }

        public Criteria andTreeidIsNull() {
            addCriterion("TREEID is null");
            return this;
        }

        public Criteria andTreeidIsNotNull() {
            addCriterion("TREEID is not null");
            return this;
        }

        public Criteria andTreeidEqualTo(String value) {
            addCriterion("TREEID =", value, "treeid");
            return this;
        }

        public Criteria andTreeidNotEqualTo(String value) {
            addCriterion("TREEID <>", value, "treeid");
            return this;
        }

        public Criteria andTreeidGreaterThan(String value) {
            addCriterion("TREEID >", value, "treeid");
            return this;
        }

        public Criteria andTreeidGreaterThanOrEqualTo(String value) {
            addCriterion("TREEID >=", value, "treeid");
            return this;
        }

        public Criteria andTreeidLessThan(String value) {
            addCriterion("TREEID <", value, "treeid");
            return this;
        }

        public Criteria andTreeidLessThanOrEqualTo(String value) {
            addCriterion("TREEID <=", value, "treeid");
            return this;
        }

        public Criteria andTreeidLike(String value) {
            addCriterion("TREEID like", value, "treeid");
            return this;
        }

        public Criteria andTreeidNotLike(String value) {
            addCriterion("TREEID not like", value, "treeid");
            return this;
        }

        public Criteria andTreeidIn(List values) {
            addCriterion("TREEID in", values, "treeid");
            return this;
        }

        public Criteria andTreeidNotIn(List values) {
            addCriterion("TREEID not in", values, "treeid");
            return this;
        }

        public Criteria andTreeidBetween(String value1, String value2) {
            addCriterion("TREEID between", value1, value2, "treeid");
            return this;
        }

        public Criteria andTreeidNotBetween(String value1, String value2) {
            addCriterion("TREEID not between", value1, value2, "treeid");
            return this;
        }

        public Criteria andTempletidIsNull() {
            addCriterion("TEMPLETID is null");
            return this;
        }

        public Criteria andTempletidIsNotNull() {
            addCriterion("TEMPLETID is not null");
            return this;
        }

        public Criteria andTempletidEqualTo(String value) {
            addCriterion("TEMPLETID =", value, "templetid");
            return this;
        }

        public Criteria andTempletidNotEqualTo(String value) {
            addCriterion("TEMPLETID <>", value, "templetid");
            return this;
        }

        public Criteria andTempletidGreaterThan(String value) {
            addCriterion("TEMPLETID >", value, "templetid");
            return this;
        }

        public Criteria andTempletidGreaterThanOrEqualTo(String value) {
            addCriterion("TEMPLETID >=", value, "templetid");
            return this;
        }

        public Criteria andTempletidLessThan(String value) {
            addCriterion("TEMPLETID <", value, "templetid");
            return this;
        }

        public Criteria andTempletidLessThanOrEqualTo(String value) {
            addCriterion("TEMPLETID <=", value, "templetid");
            return this;
        }

        public Criteria andTempletidLike(String value) {
            addCriterion("TEMPLETID like", value, "templetid");
            return this;
        }

        public Criteria andTempletidNotLike(String value) {
            addCriterion("TEMPLETID not like", value, "templetid");
            return this;
        }

        public Criteria andTempletidIn(List values) {
            addCriterion("TEMPLETID in", values, "templetid");
            return this;
        }

        public Criteria andTempletidNotIn(List values) {
            addCriterion("TEMPLETID not in", values, "templetid");
            return this;
        }

        public Criteria andTempletidBetween(String value1, String value2) {
            addCriterion("TEMPLETID between", value1, value2, "templetid");
            return this;
        }

        public Criteria andTempletidNotBetween(String value1, String value2) {
            addCriterion("TEMPLETID not between", value1, value2, "templetid");
            return this;
        }
    }
}