package com.yapu.system.dao.impl;

import java.util.HashMap;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.yapu.system.dao.itf.SysErrorlogDAO;
import com.yapu.system.entity.SysErrorlog;
import com.yapu.system.entity.SysErrorlogExample;

public class SysErrorlogDAOImpl extends SqlMapClientDaoSupport implements SysErrorlogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysErrorlogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int countByExample(SysErrorlogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SYS_ERRORLOG.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int deleteByExample(SysErrorlogExample example) {
        int rows = getSqlMapClientTemplate().delete("SYS_ERRORLOG.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int deleteByPrimaryKey(String errorlogid) {
        SysErrorlog key = new SysErrorlog();
        key.setErrorlogid(errorlogid);
        int rows = getSqlMapClientTemplate().delete("SYS_ERRORLOG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void insert(SysErrorlog record) {
        getSqlMapClientTemplate().insert("SYS_ERRORLOG.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void insertSelective(SysErrorlog record) {
        getSqlMapClientTemplate().insert("SYS_ERRORLOG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public List selectByExample(SysErrorlogExample example) {
        List list = getSqlMapClientTemplate().queryForList("SYS_ERRORLOG.ibatorgenerated_selectByExample", example);
        return list;
    }
    /*
     * (non-Javadoc)
     * @see com.yapu.system.dao.itf.SysErrorlogDAO#selectByMapPage(java.util.HashMap)
     */
    public List selectByMapPage(HashMap map) {
		List list = getSqlMapClientTemplate().queryForList("SYS_ERRORLOG.ibatorgenerated_selectByExamplePage", map);
		return list;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysErrorlog selectByPrimaryKey(String errorlogid) {
        SysErrorlog key = new SysErrorlog();
        key.setErrorlogid(errorlogid);
        SysErrorlog record = (SysErrorlog) getSqlMapClientTemplate().queryForObject("SYS_ERRORLOG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByExampleSelective(SysErrorlog record, SysErrorlogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_ERRORLOG.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByExample(SysErrorlog record, SysErrorlogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_ERRORLOG.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByPrimaryKeySelective(SysErrorlog record) {
        int rows = getSqlMapClientTemplate().update("SYS_ERRORLOG.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByPrimaryKey(SysErrorlog record) {
        int rows = getSqlMapClientTemplate().update("SYS_ERRORLOG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_ERRORLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private static class UpdateByExampleParms extends SysErrorlogExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysErrorlogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}