package com.yapu.system.dao.impl;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.yapu.system.dao.itf.SysFunctionDAO;
import com.yapu.system.entity.SysFunction;
import com.yapu.system.entity.SysFunctionExample;

public class SysFunctionDAOImpl extends SqlMapClientDaoSupport implements SysFunctionDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public SysFunctionDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int countByExample(SysFunctionExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SYS_FUNCTION.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int deleteByExample(SysFunctionExample example) {
        int rows = getSqlMapClientTemplate().delete("SYS_FUNCTION.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int deleteByPrimaryKey(String functionid) {
        SysFunction key = new SysFunction();
        key.setFunctionid(functionid);
        int rows = getSqlMapClientTemplate().delete("SYS_FUNCTION.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void insert(SysFunction record) {
        getSqlMapClientTemplate().insert("SYS_FUNCTION.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public void insertSelective(SysFunction record) {
        getSqlMapClientTemplate().insert("SYS_FUNCTION.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public List selectByExample(SysFunctionExample example) {
        List list = getSqlMapClientTemplate().queryForList("SYS_FUNCTION.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public SysFunction selectByPrimaryKey(String functionid) {
        SysFunction key = new SysFunction();
        key.setFunctionid(functionid);
        SysFunction record = (SysFunction) getSqlMapClientTemplate().queryForObject("SYS_FUNCTION.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int updateByExampleSelective(SysFunction record, SysFunctionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_FUNCTION.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int updateByExample(SysFunction record, SysFunctionExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_FUNCTION.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int updateByPrimaryKeySelective(SysFunction record) {
        int rows = getSqlMapClientTemplate().update("SYS_FUNCTION.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    public int updateByPrimaryKey(SysFunction record) {
        int rows = getSqlMapClientTemplate().update("SYS_FUNCTION.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_FUNCTION
     *
     * @ibatorgenerated Sat Nov 13 12:15:56 GMT+08:00 2010
     */
    private static class UpdateByExampleParms extends SysFunctionExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysFunctionExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}