package com.yapu.system.dao.impl;

import java.util.HashMap;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.yapu.system.dao.itf.SysLoginlogDAO;
import com.yapu.system.entity.SysLoginlog;
import com.yapu.system.entity.SysLoginlogExample;

public class SysLoginlogDAOImpl extends SqlMapClientDaoSupport implements SysLoginlogDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysLoginlogDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int countByExample(SysLoginlogExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("SYS_LOGINLOG.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int deleteByExample(SysLoginlogExample example) {
        int rows = getSqlMapClientTemplate().delete("SYS_LOGINLOG.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int deleteByPrimaryKey(String loginlogid) {
        SysLoginlog key = new SysLoginlog();
        key.setLoginlogid(loginlogid);
        int rows = getSqlMapClientTemplate().delete("SYS_LOGINLOG.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void insert(SysLoginlog record) {
        getSqlMapClientTemplate().insert("SYS_LOGINLOG.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void insertSelective(SysLoginlog record) {
        getSqlMapClientTemplate().insert("SYS_LOGINLOG.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public List selectByExample(SysLoginlogExample example) {
        List list = getSqlMapClientTemplate().queryForList("SYS_LOGINLOG.ibatorgenerated_selectByExample", example);
        return list;
    }
    /*
     * (non-Javadoc)
     * @see com.yapu.system.dao.itf.SysLoginlogDAO#selectByMapPage(java.util.HashMap)
     */
    public List selectByMapPage(HashMap map) {
    	List list = getSqlMapClientTemplate().queryForList("SYS_LOGINLOG.ibatorgenerated_selectByExamplePage", map);
		return list;
	}

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public SysLoginlog selectByPrimaryKey(String loginlogid) {
        SysLoginlog key = new SysLoginlog();
        key.setLoginlogid(loginlogid);
        SysLoginlog record = (SysLoginlog) getSqlMapClientTemplate().queryForObject("SYS_LOGINLOG.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByExampleSelective(SysLoginlog record, SysLoginlogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_LOGINLOG.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByExample(SysLoginlog record, SysLoginlogExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("SYS_LOGINLOG.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByPrimaryKeySelective(SysLoginlog record) {
        int rows = getSqlMapClientTemplate().update("SYS_LOGINLOG.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public int updateByPrimaryKey(SysLoginlog record) {
        int rows = getSqlMapClientTemplate().update("SYS_LOGINLOG.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table SYS_LOGINLOG
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private static class UpdateByExampleParms extends SysLoginlogExample {
        private Object record;

        public UpdateByExampleParms(Object record, SysLoginlogExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}