package com.yapu.system.entity;

public class SysAccountRole {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ACCOUNT_ROLE.ACCOUNT_ROLE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String accountRoleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ACCOUNT_ROLE.ROLEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String roleid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ACCOUNT_ROLE.ACCOUNTID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String accountid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ACCOUNT_ROLE.ACCOUNT_ROLE_ID
     *
     * @return the value of SYS_ACCOUNT_ROLE.ACCOUNT_ROLE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getAccountRoleId() {
        return accountRoleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ACCOUNT_ROLE.ACCOUNT_ROLE_ID
     *
     * @param accountRoleId the value for SYS_ACCOUNT_ROLE.ACCOUNT_ROLE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setAccountRoleId(String accountRoleId) {
        this.accountRoleId = accountRoleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ACCOUNT_ROLE.ROLEID
     *
     * @return the value of SYS_ACCOUNT_ROLE.ROLEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ACCOUNT_ROLE.ROLEID
     *
     * @param roleid the value for SYS_ACCOUNT_ROLE.ROLEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ACCOUNT_ROLE.ACCOUNTID
     *
     * @return the value of SYS_ACCOUNT_ROLE.ACCOUNTID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ACCOUNT_ROLE.ACCOUNTID
     *
     * @param accountid the value for SYS_ACCOUNT_ROLE.ACCOUNTID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }
}