package com.yapu.system.entity;

import com.yapu.system.common.BaseEntity;



public class SysErrorlog extends BaseEntity{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ERRORLOG.ERRORLOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String errorlogid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ERRORLOG.FUNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String funname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ERRORLOG.ERRORTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String errortime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ERRORLOG.ERRORDOC
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String errordoc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ERRORLOG.ERRORLOGID
     *
     * @return the value of SYS_ERRORLOG.ERRORLOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getErrorlogid() {
        return errorlogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ERRORLOG.ERRORLOGID
     *
     * @param errorlogid the value for SYS_ERRORLOG.ERRORLOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setErrorlogid(String errorlogid) {
        this.errorlogid = errorlogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ERRORLOG.FUNNAME
     *
     * @return the value of SYS_ERRORLOG.FUNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getFunname() {
        return funname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ERRORLOG.FUNNAME
     *
     * @param funname the value for SYS_ERRORLOG.FUNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setFunname(String funname) {
        this.funname = funname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ERRORLOG.ERRORTIME
     *
     * @return the value of SYS_ERRORLOG.ERRORTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getErrortime() {
        return errortime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ERRORLOG.ERRORTIME
     *
     * @param errortime the value for SYS_ERRORLOG.ERRORTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setErrortime(String errortime) {
        this.errortime = errortime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ERRORLOG.ERRORDOC
     *
     * @return the value of SYS_ERRORLOG.ERRORDOC
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getErrordoc() {
        return errordoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ERRORLOG.ERRORDOC
     *
     * @param errordoc the value for SYS_ERRORLOG.ERRORDOC
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setErrordoc(String errordoc) {
        this.errordoc = errordoc;
    }
}