package com.yapu.system.entity;

import com.yapu.system.common.BaseEntity;



public class SysLoginlog extends BaseEntity{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_LOGINLOG.LOGINLOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String loginlogid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_LOGINLOG.ACCOUNTCODE
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String accountcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_LOGINLOG.USERNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_LOGINLOG.LOGINTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String logintime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_LOGINLOG.OUTTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String outtime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_LOGINLOG.LOGINIP
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String loginip;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_LOGINLOG.LOGINLOGID
     *
     * @return the value of SYS_LOGINLOG.LOGINLOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getLoginlogid() {
        return loginlogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_LOGINLOG.LOGINLOGID
     *
     * @param loginlogid the value for SYS_LOGINLOG.LOGINLOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setLoginlogid(String loginlogid) {
        this.loginlogid = loginlogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_LOGINLOG.ACCOUNTCODE
     *
     * @return the value of SYS_LOGINLOG.ACCOUNTCODE
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getAccountcode() {
        return accountcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_LOGINLOG.ACCOUNTCODE
     *
     * @param accountcode the value for SYS_LOGINLOG.ACCOUNTCODE
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_LOGINLOG.USERNAME
     *
     * @return the value of SYS_LOGINLOG.USERNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_LOGINLOG.USERNAME
     *
     * @param username the value for SYS_LOGINLOG.USERNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_LOGINLOG.LOGINTIME
     *
     * @return the value of SYS_LOGINLOG.LOGINTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_LOGINLOG.LOGINTIME
     *
     * @param logintime the value for SYS_LOGINLOG.LOGINTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_LOGINLOG.OUTTIME
     *
     * @return the value of SYS_LOGINLOG.OUTTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_LOGINLOG.OUTTIME
     *
     * @param outtime the value for SYS_LOGINLOG.OUTTIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOuttime(String outtime) {
        this.outtime = outtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_LOGINLOG.LOGINIP
     *
     * @return the value of SYS_LOGINLOG.LOGINIP
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_LOGINLOG.LOGINIP
     *
     * @param loginip the value for SYS_LOGINLOG.LOGINIP
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }
}