package com.yapu.system.entity;

public class SysOrgRole {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_ROLE.ORG_ROLE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String orgRoleId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_ROLE.ORGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String orgid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_ORG_ROLE.ROLEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String roleid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_ROLE.ORG_ROLE_ID
     *
     * @return the value of SYS_ORG_ROLE.ORG_ROLE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOrgRoleId() {
        return orgRoleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_ROLE.ORG_ROLE_ID
     *
     * @param orgRoleId the value for SYS_ORG_ROLE.ORG_ROLE_ID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOrgRoleId(String orgRoleId) {
        this.orgRoleId = orgRoleId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_ROLE.ORGID
     *
     * @return the value of SYS_ORG_ROLE.ORGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_ROLE.ORGID
     *
     * @param orgid the value for SYS_ORG_ROLE.ORGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_ORG_ROLE.ROLEID
     *
     * @return the value of SYS_ORG_ROLE.ROLEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_ORG_ROLE.ROLEID
     *
     * @param roleid the value for SYS_ORG_ROLE.ROLEID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
}