package com.yapu.system.entity;

import com.yapu.system.common.BaseEntity;



public class SysOperatelog extends BaseEntity{
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_OPERATELOG.OPERATELOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String operatelogid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_OPERATELOG.ACCOUNTCODE
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String accountcode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_OPERATELOG.USERNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String username;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_OPERATELOG.FUNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String funname;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_OPERATELOG.OPERATETIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String operatetime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column SYS_OPERATELOG.LOGDOC
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    private String logdoc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_OPERATELOG.OPERATELOGID
     *
     * @return the value of SYS_OPERATELOG.OPERATELOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOperatelogid() {
        return operatelogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_OPERATELOG.OPERATELOGID
     *
     * @param operatelogid the value for SYS_OPERATELOG.OPERATELOGID
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOperatelogid(String operatelogid) {
        this.operatelogid = operatelogid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_OPERATELOG.ACCOUNTCODE
     *
     * @return the value of SYS_OPERATELOG.ACCOUNTCODE
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getAccountcode() {
        return accountcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_OPERATELOG.ACCOUNTCODE
     *
     * @param accountcode the value for SYS_OPERATELOG.ACCOUNTCODE
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setAccountcode(String accountcode) {
        this.accountcode = accountcode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_OPERATELOG.USERNAME
     *
     * @return the value of SYS_OPERATELOG.USERNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_OPERATELOG.USERNAME
     *
     * @param username the value for SYS_OPERATELOG.USERNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_OPERATELOG.FUNNAME
     *
     * @return the value of SYS_OPERATELOG.FUNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getFunname() {
        return funname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_OPERATELOG.FUNNAME
     *
     * @param funname the value for SYS_OPERATELOG.FUNNAME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setFunname(String funname) {
        this.funname = funname;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_OPERATELOG.OPERATETIME
     *
     * @return the value of SYS_OPERATELOG.OPERATETIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_OPERATELOG.OPERATETIME
     *
     * @param operatetime the value for SYS_OPERATELOG.OPERATETIME
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setOperatetime(String operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column SYS_OPERATELOG.LOGDOC
     *
     * @return the value of SYS_OPERATELOG.LOGDOC
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public String getLogdoc() {
        return logdoc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column SYS_OPERATELOG.LOGDOC
     *
     * @param logdoc the value for SYS_OPERATELOG.LOGDOC
     *
     * @ibatorgenerated Fri Nov 12 20:49:06 GMT+08:00 2010
     */
    public void setLogdoc(String logdoc) {
        this.logdoc = logdoc;
    }
}